language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.
ghc:
  - 7.8.3
  - 7.6.3
  # - 7.4.2
  # - 7.2.2
  # - 7.0.4

install:
  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  # New happy needed for haskell-src-exts
  - cabal install happy
  # New new alex for us
  - cabal install alex
  # And epic
  - sudo apt-get install libgc-dev
  - cabal install epic
  # Get the std-lib
  - make std-lib
  # GO GO GO
  - cabal install --only-dependencies -j
  - make install-fix-agda-whitespace

script:
  # We first build so that we get some output for travis -- otherwise
  # it'll stall the build
  - cabal build -v2
  - make install-bin
  - make doc
  # Right now tests are broken.
  # - make test

notifications:
  email: false
