language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.
ghc:
  - 7.8.3
  # - 7.6.3
  # - 7.4.2
  # - 7.2.2
  # - 7.0.4

install:
  # New happy needed for haskell-src-exts
  - cabal install happy
  - cabal install --only-dependencies -j

script:
  - cabal build -v2

# Just for the time being while things don't work
notifications:
  email: false