language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

# We use the word 'test' in a broad sense (e.g. it includes the Agda
# test suite, the benchmark suite, the compilation with a specific set
# of dependencies, the testing of other programs like `hTags`, etc.) The
# tests are divided according to whether or not require the standard
# library.
#
# The current tests non-requiring the standard library are:
#
# make check-whitespace
# make succeed
# make fail
# make interaction
# make interactive
# make latex-test
# make examples
# make api-test
# make tests
# make TAGS (testing the hTags program)
#
# The current tests requiring the standard library are:
#
# make library-test
# make lib-succeed
# make compiler-test
# make benchmark-without-logs
env:
  - TEST=ghc-7.8.4-transformers-0.3.0.0
  - TEST=non_require_stdlib
  - TEST=require_stdlib

install:
  # Asking for the shell.
  - echo $SHELL

  # TODO (13 June 2015): Don't install cabal-install, Alex and Happy when
  # $TEST=ghc-7.8.4-transformers-0.3.0.0 and GHC version is different to 7.8.4.

  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  - cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # New new Alex for us
  - cabal install alex

  # The GHC version.
  - GHC_VERSION_TRAVIS=`ghc --numeric-version`

  ############################################################################
  # Installing dependencies

  # In Travis (because the Haskell platform is installed?) Cabal needs the
  # `--avoid-reinstalls` flag on GHC 7.4.2 and 7.6.3, else it will complain
  # about breaking previously installed packages [Issue 1520].

  # Note: `cabal install` doesn't set up the number of jobs by default
  # (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case $TEST in
      "non_require_stdlib")
        if [ $GHC_VERSION_TRAVIS = 7.4.2 -o $GHC_VERSION_TRAVIS = 7.6.3 ]; then
           cabal install --avoid-reinstalls --only-dependencies; else cabal install --only-dependencies;
        fi
        ;;

      "require_stdlib")
        if [ $GHC_VERSION_TRAVIS = 7.4.2 -o $GHC_VERSION_TRAVIS = 7.6.3 ]; then
           cabal install --enable-tests --avoid-reinstalls --only-dependencies; else cabal install --enable-tests --only-dependencies;
        fi
        ;;
    esac

  ############################################################################
  # Running `cabal configure`

  - export BUILD_DIR=$PWD/dist

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case $TEST in
      "non_require_stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR
        ;;

      "require_stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR --enable-tests
        ;;
    esac

  ############################################################################
  # Running `cabal build`

  # Note: `cabal build` sets up the number of jobs to $ncpus by default.
  # (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

  - case $TEST in
      "non_require_stdlib" | "require_stdlib")
        cabal build -v2 --builddir=$BUILD_DIR
        ;;
    esac

  ############################################################################
  # Running `cabal install`

  # The `enable-test` option is required only if $TEST=require_stdlib.
  - case $TEST in
      "non_require_stdlib")
        cabal install -v2 --builddir=$BUILD_DIR
        ;;

      "require_stdlib")
        cabal install -v2 --builddir=$BUILD_DIR --enable-tests
        ;;
    esac

  ############################################################################

  # The Epic backend has been removed. See Issue 1481.
  # Epic installation.
  # - sudo apt-get install libgc-dev
  # - cabal install epic

  # Required packages for running the LaTeX test-suite.
  #
  # Remark (19 April 2015). Travis (i.e. Ubuntu 12.04) uses an outdated
  # TeX Live 2009. The LaTeX test-suite requires the unicode-math package
  # which is not available in this version of TeX Live (see Issue 1022).

  # The LaTeX test-suite doesn't require the standard library.
  - if [ $TEST = "non_require_stdlib" ]; then
       sudo add-apt-repository ppa:texlive-backports/ppa -y;
       sudo apt-get update;
       sudo apt-get install texlive;
       sudo apt-get install texlive-latex-extra;
       sudo apt-get install texlive-xetex;
       sudo apt-get install texlive-math-extra;
       sudo apt-get install texlive-fonts-extra;
    fi

  ############################################################################
  # Getting the standard library

  - if [ $TEST = "require_stdlib" ]; then
       make up-to-date-std-lib;
    fi

  ############################################################################
  # Testing compilation with transformers 0.3.0.0 which is shipped with
  # GHC 7.8.* [Issue 1156].

  - if [ $TEST = "ghc-7.8.4-transformers-0.3.0.0" -a $GHC_VERSION_TRAVIS = 7.8.4 ]; then
       cabal install --only-dependencies --constraint=transformers==0.3.0.0 ;
       cabal configure -v2 --builddir=$BUILD_DIR --constraint=transformers==0.3.0.0;
       cabal build -v2 --builddir=$BUILD_DIR;
    fi

  ############################################################################
  # Installing fix-agda-whitespace

  - if [ $TEST = "non_require_stdlib" ]; then
       make install-fix-agda-whitespace;
    fi

  ############################################################################

script:
  # Right now Haddock doesn't work, presumably because it consumes too
  # much memory.
  # - cabal haddock

  # TODO (07 May 2015): I couldn't add the following documentation inside the
  # case statement:
  # 1. Testing the hTags program.

  - case $TEST in
      "non_require_stdlib")
        make check-whitespace &&

        make BUILD_DIR=$BUILD_DIR succeed &&

        make BUILD_DIR=$BUILD_DIR fail &&

        make BUILD_DIR=$BUILD_DIR interaction &&

        make BUILD_DIR=$BUILD_DIR interactive &&

        make BUILD_DIR=$BUILD_DIR latex-test &&

        make BUILD_DIR=$BUILD_DIR examples &&

        make BUILD_DIR=$BUILD_DIR api-test &&

        make BUILD_DIR=$BUILD_DIR tests &&

        make BUILD_DIR=$BUILD_DIR TAGS
        ;;

      "require_stdlib")
        make BUILD_DIR=$BUILD_DIR library-test &&

        make BUILD_DIR=$BUILD_DIR lib-succeed &&

        make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR compiler-test &&

        make BUILD_DIR=$BUILD_DIR benchmark-without-logs
        ;;
    esac

# Builds are loooong, we want to send an email as fast as possible.
matrix:
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.
branches:
  only:
    - master
    - maint-2.4.2
