language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.
ghc:
  - 7.8.3
  - 7.6.3
  # - 7.4.2
  # - 7.2.2
  # - 7.0.4

install:
  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  # New happy needed for haskell-src-exts
  - cabal install happy
  # New new alex for us
  - cabal install alex
  # And epic
  - sudo apt-get install libgc-dev
  - cabal install epic
  # Get the std-lib
  - make std-lib
  # GO GO GO
  - cabal install --only-dependencies -j
  - make install-fix-agda-whitespace

script:
  - cabal install --disable-library-profiling --disable-documentation
  # Right now haddock doesn't work, presumably because it consumes too
  # much memory.
  # - cabal haddock
  - make check-whitespace
  - make succeed
  # Right now fail tests are broken, the output differs
  # - make fail
  - make interaction
  # Travis doesn't have latex, not sure if we should install it
  # - make latex-test
  - make examples
  - make library-test
  - make lib-succeed
  - make compiler-test
  - make epic-test
  - make api-test
  - make tests

# notifications:
#   email: false
